# config/model/default.yaml
backbone: vgg11        # Möglichkeiten: vgg11, vgg16
pretrained: true       # vortrainierte ImageNet-Gewichte
num_classes: 5         # standardmäßig 5, für BSData beim Lauf auf 2 überschreiben
